### ISSUE TITLE
maybe artifacts path has changed

### ISSUE THREAD

**Issue by konojunya** [Naturalclar/klank#31]
Maybe the artifacts response has changed.

https://circleci.com/docs/api/#artifacts

docs:
```
[ {
  "path" : "raw-test-output/go-test-report.xml",
  "pretty_path" : "raw-test-output/go-test-report.xml",
  "node_index" : 0,
  "url" : "https://24-88881093-gh.circle-artifacts.com/0/raw-test-output/go-test-report.xml"
}, {
  "path" : "raw-test-output/go-test.out",
  "pretty_path" : "raw-test-output/go-test.out",
  "node_index" : 0,
  "url" : "https://24-88881093-gh.circle-artifacts.com/0/raw-test-output/go-test.out"
} ]
```

master:
https://github.com/moxci/moxci/blob/aca1f28237c3510adebcc636c620edae1a33fa66/src/get-artifact.ts#L16-L21

Would you like me to send pull request?

**Comment by Naturalclar** [comment]
@konojunya Thank you! If you can send me a pull request, that will be great!

**Comment by konojunya** [comment]
@Naturalclar I'm sorry, this is a misunderstanding. Since targetUrl can be filtered even by looking at url and path, no modification was required :)
